apiVersion: apps/v1
kind: Deployment
metadata:
   name: wisecow
   namespace: default
spec:
   replicas: 1
   selector:
      matchLabels:
         app: wisecow
   template:
      metadata:
         labels:
            app: wisecow
      spec:
         containers:
            - name: wisecow
              image: benzz9497/wisecow:latest
              ports:
              - containerPort: 4499
---
apiVersion: v1
kind: Service
metadata:
  name: wisecow-entrypoint
spec:
  type: NodePort
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4499
      nodePort: 30100